site_name: Bodhi Prediction Market Wiki
theme:
  name: readthedocs
  custom_dir: custom_theme
pages:
  - Home: index.md
  - Bodhi Token: bodhitoken.md
  - Contract Deployment: deployment.md
  - Help: help.md