site_name: Bodhi Prediction Market Wiki
theme:
  name: readthedocs
  custom_dir: custom_theme
pages:
  - Home: index.md
  - Bodhi Token:
    - Info: bodhi_token/info.md
    - Qtum Wallet Mobile: bodhi_token/qtum_wallet_mobile.md
    - Qtum Clients: bodhi_token/qtum_clients.md
    - QBao: bodhi_token/qbao.md
  - Contract Deployment: deployment.md
  - Help: help.md