site_name: Bodhi Prediction Market Wiki
theme:
  name: readthedocs
  custom_dir: custom_theme
pages:
  - Home: index.md
  - Bodhi Token:
    - Info: bodhi_token/info.md
    - QBao (Mobile): bodhi_token/qbao.md
    - Qtum Wallet (Mobile): bodhi_token/qtum_wallet_mobile.md
    - QT Wallet (Desktop): bodhi_token/qt_wallet_desktop.md
    - Qtum-cli (Desktop): bodhi_token/qtum_cli.md
  - Bodhi Core:
    - EventFactory: bodhi_core/event_factory.md
    - TopicEvent: bodhi_core/topic_event.md
    - OracleFactory: bodhi_core/oracle_factory.md
    - CentralizedOracle: bodhi_core/centralized_oracle.md
    - DecentralizedOracle: bodhi_core/decentralized_oracle.md
    - Logs: bodhi_core/logs.md
  - Qtum:
    - QT Wallet (Desktop): qtum/qt_wallet.md 
  - Contract Deployment: deployment.md
  - First Time User Guide: first_time_user_guide.md
  - Help: help.md
extra_javascript:
  ['https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.10/clipboard.min.js','js/clipboard.js']
extra_css:
  ['https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css', 'css/custom.css']
